// Generated by dia2code
#ifndef STATE__BOW__H
#define STATE__BOW__H


namespace state {
  class Weapon;
}

#include "Weapon.h"

namespace state {

  /// class Bow - 
  class Bow : public state::Weapon {
    // Operations
  public:
    Bow (int id, int damage);
    ~Bow ();
    bool const isCloseCombat ();
    Weapon* clone () const;
    // Setters and Getters
  };

};

#endif
