// Generated by dia2code
#ifndef STATE__BOWMAN__H
#define STATE__BOWMAN__H


namespace state {
  class Unit;
}

#include "TeamId.h"
#include "RaceTypeId.h"
#include "Unit.h"

namespace state {

  /// class Bowman - 
  class Bowman : public state::Unit {
    // Operations
  public:
    Bowman (TeamId team, int positionX, int positionY, RaceTypeId race);
    Unit* clone () const;
    bool equals (const Unit& other) const;
    // Setters and Getters
  };

};

#endif
