// Generated by dia2code
#ifndef STATE__CASTLE__H
#define STATE__CASTLE__H


namespace state {
  class Terrain;
}

#include "Terrain.h"

namespace state {

  /// class Castle - 
  class Castle : public state::Terrain {
    // Operations
  public:
    Castle (int positionX = 0, int positionY = 0);
    Terrain* clone () const;
    // Setters and Getters
  };

};

#endif
