// Generated by dia2code
#ifndef STATE__DEFAULT__H
#define STATE__DEFAULT__H


namespace state {
  class Terrain;
}

#include "Terrain.h"

namespace state {

  /// class Default - 
  class Default : public state::Terrain {
    // Operations
  public:
    Default (int id, int positionX = 10, int positionY = 10);
    Terrain* clone () const;
    // Setters and Getters
  };

};

#endif
