// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    TOP     = 0,
    TOP_RIGHT     = 1,
    BOT_RIGHT     = 2,
    BOT     = 3,
    BOT_LEFT     = 4,
    TOP_LEFT     = 5
  };

};

#endif
