// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    INVALID_DIRECTION     = 0,
    TOP     = 1,
    TOP_RIGHT     = 2,
    BOT_RIGHT     = 3,
    BOT     = 4,
    BOT_LEFT     = 5,
    TOP_LEFT     = 6
  };

};

#endif
