// Generated by dia2code
#ifndef STATE__HOUSE__H
#define STATE__HOUSE__H


namespace state {
  class Terrain;
}

#include "TeamId.h"
#include "Terrain.h"

namespace state {

  /// class House - 
  class House : public state::Terrain {
    // Attributes
  private:
    TeamId teamId;
    // Operations
  public:
    House (int positionX = 0, int positionY = 0);
    void claim (TeamId teamId);
    Terrain* clone () const;
    void setTeamId (TeamId teamId);
    const TeamId& getTeamId () const;
    bool equals (const Terrain& other) const;
    // Setters and Getters
  };

};

#endif
