// Generated by dia2code
#ifndef STATE__HOUSE__H
#define STATE__HOUSE__H


namespace state {
  class Terrain;
}

#include "Terrain.h"

namespace state {

  /// class House - 
  class House : public state::Terrain {
    // Attributes
  private:
    int teamId;
    // Operations
  public:
    House (int id, int positionX = 0, int positionY = 0);
    void claim (int teamId);
    Terrain* clone () const;
    // Setters and Getters
  };

};

#endif
