// Generated by dia2code
#ifndef STATE__LEADER__H
#define STATE__LEADER__H


namespace state {
  class Unit;
}

#include "TeamId.h"
#include "RaceTypeId.h"
#include "Unit.h"

namespace state {

  /// class Leader - 
  class Leader : public state::Unit {
    // Operations
  public:
    Leader (TeamId team, int positionX, int positionY, RaceTypeId race);
    Unit* clone () const;
    bool equals (const Unit& other) const;
    // Setters and Getters
  };

};

#endif
