// Generated by dia2code
#ifndef STATE__RACETYPEID__H
#define STATE__RACETYPEID__H


namespace state {

  enum RaceTypeId {
    INVALIDRACE     = 0,
    HUMAN     = 1,
    ORC     = 2
  };

};

#endif
