// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class Board;
}

#include "Board.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    Board board;
    // Operations
  public:
    State ();
    Board& getBoard ();
    // Setters and Getters
  };

};

#endif
