// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class Board;
  class Observable;
}

#include "Board.h"
#include "TeamId.h"
#include "Observable.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  private:
    Board board;
  protected:
    int turn     = 0;
    int epoch     = 0;
    // Operations
  public:
    State ();
    Board& getBoard ();
    const Board& getBoard () const;
    const TeamId getCurrentTeam () const;
    void endTurn ();
    // Setters and Getters
    int getTurn() const;
    void setTurn(int turn);
    int getEpoch() const;
    void setEpoch(int epoch);
  };

};

#endif
