// Generated by dia2code
#ifndef STATE__SWORDMAN__H
#define STATE__SWORDMAN__H


namespace state {
  class Unit;
}

#include "Unit.h"

namespace state {

  /// class Swordman - 
  class Swordman : public state::Unit {
    // Operations
  public:
    Swordman (int id, int team, int positionX = 0, int positionY = 0);
    Unit* clone () const;
    // Setters and Getters
  };

};

#endif
