// Generated by dia2code
#ifndef STATE__SWORDMAN__H
#define STATE__SWORDMAN__H


namespace state {
  class Unit;
}

#include "TeamId.h"
#include "RaceTypeId.h"
#include "Unit.h"

namespace state {

  /// class Swordman - 
  class Swordman : public state::Unit {
    // Operations
  public:
    Swordman (TeamId team, int positionX, int positionY, RaceTypeId race);
    Unit* clone () const;
    // Setters and Getters
  };

};

#endif
