// Generated by dia2code
#ifndef STATE__SWORD__H
#define STATE__SWORD__H


namespace state {
  class Weapon;
}

#include "Weapon.h"

namespace state {

  /// class Sword - 
  class Sword : public state::Weapon {
    // Operations
  public:
    Sword (int id, int damage);
    ~Sword ();
    bool const isCloseCombat ();
    Weapon* clone () const;
    // Setters and Getters
  };

};

#endif
