// Generated by dia2code
#ifndef STATE__TEAM__H
#define STATE__TEAM__H

#include <map>

namespace state {
  class Team;
}

#include "TeamId.h"
#include "RaceTypeId.h"
#include "UnitTypeId.h"

namespace state {

  /// class Team - 
  class Team {
    // Attributes
  private:
    static const std::map<UnitTypeId, int> unitsPrices;
  protected:
    TeamId id;
    int gold;
    int nbHouses;
    RaceTypeId race;
    // Operations
  public:
    Team (TeamId teamId, RaceTypeId race);
    bool verifyGold (UnitTypeId unitTypeId) const;
    void withdrawGold (UnitTypeId unitTypeId);
    void generateGold ();
    void addHouse ();
    void removeHouse ();
    bool equals (const Team& other) const;
    Team* clone () const;
    // Setters and Getters
    TeamId getId() const;
    void setId(TeamId id);
    int getGold() const;
    void setGold(int gold);
    int getNbHouses() const;
    void setNbHouses(int nbHouses);
    RaceTypeId getRace() const;
    void setRace(RaceTypeId race);
  };

};

#endif
