// Generated by dia2code
#ifndef STATE__TERRAIN__H
#define STATE__TERRAIN__H


namespace state {
  class Terrain;
}

#include "TerrainTypeId.h"

namespace state {

  /// class Terrain - 
  class Terrain {
    // Associations
    // Attributes
  protected:
    int id     = 0;
    int positionX;
    int positionY;
    TerrainTypeId typeId     = TerrainTypeId::GRASS;
    int movementCost     = 1;
    // Operations
  public:
    Terrain ();
    virtual ~Terrain ();
    TerrainTypeId getTypeId () const;
    int getId () const;
    int getMovementCost () const;
    virtual Terrain* clone () const = 0;
    // Setters and Getters
    void setId(int id);
    int getPositionX() const;
    void setPositionX(int positionX);
    int getPositionY() const;
    void setPositionY(int positionY);
    void setTypeId(TerrainTypeId typeId);
    void setMovementCost(int movementCost);
  };

};

#endif
