// Generated by dia2code
#ifndef STATE__TERRAINTYPEID__H
#define STATE__TERRAINTYPEID__H


namespace state {

  enum TerrainTypeId {
    GRASS     = 1,
    FOREST     = 2,
    WATER     = 3,
    HOUSE     = 4,
    CASTLE     = 5,
    WALL     = 6
  };

};

#endif
