// Generated by dia2code
#ifndef STATE__UNITTYPEID__H
#define STATE__UNITTYPEID__H


namespace state {

  enum UnitTypeId {
    INVALID_UNIT     = 0,
    LEADER     = 1,
    SWORDMAN     = 2,
    BOWMAN     = 3
  };

};

#endif
