// Generated by dia2code
#ifndef STATE__WEAPONTYPEID__H
#define STATE__WEAPONTYPEID__H


namespace state {

  enum WeaponTypeId {
    INVALIDWEAPON     = 0,
    SWORD     = 1,
    BOW     = 2
  };

};

#endif
