// Generated by dia2code
#ifndef RENDER__BOARDLAYER__H
#define RENDER__BOARDLAYER__H


namespace state {
  class Board;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/Board.h"

namespace render {

  /// class BoardLayer - 
  class BoardLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::Board& board;
    // Operations
  public:
    BoardLayer (const state::Board& board);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
