// Generated by dia2code
#ifndef RENDER__DEBUGLAYER__H
#define RENDER__DEBUGLAYER__H

#include <vector>

namespace state {
  class State;
};
namespace render {
  class Layer;
}

#include "state/State.h"
#include "Layer.h"

namespace render {

  /// class DebugLayer - 
  class DebugLayer : public render::Layer {
    // Attributes
  private:
    state::State state;
    // Operations
  public:
    DebugLayer (const state::State& state);
    void initSurface ();
    void printPathMap (const std::vector<int>& weights);
    // Setters and Getters
  };

};

#endif
