// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>

namespace render {
  class Surface;
  class TileSet;
}

#include "Surface.h"
#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  private:
    std::unique_ptr<Surface> surface;
    std::shared_ptr<TileSet> tileset;
    // Operations
  public:
    Layer ();
    virtual ~Layer ();
    const Surface* getSurface () const;
    void setSurface (Surface* surface);
    virtual void initSurface () = 0;
    // Setters and Getters
  };

};

#endif
