// Generated by dia2code
#ifndef RENDER__MENULAYER__H
#define RENDER__MENULAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"

namespace render {

  /// class MenuLayer - 
  class MenuLayer : public render::Layer {
    // Operations
  public:
    MenuLayer ();
    void initSurface ();
    // Setters and Getters
  };

};

#endif
