// Generated by dia2code
#ifndef RENDER__MENUTILESET__H
#define RENDER__MENUTILESET__H

#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class MenuTileSet - 
  class MenuTileSet : public render::TileSet {
    // Operations
  public:
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (char menu) const;
    // Setters and Getters
  };

};

#endif
