// Generated by dia2code
#ifndef RENDER__MENUTYPEID__H
#define RENDER__MENUTYPEID__H


namespace render {

  enum MenuTypeId {
    MENU_TOP     = 1,
    MENU_LEFT     = 2,
    MENU_GOLD     = 3,
    MENU_HOUSE     = 4
  };

};

#endif
