// Generated by dia2code
#ifndef RENDER__MENUTILESET__H
#define RENDER__MENUTILESET__H

#include <map>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "TileSet.h"
#include "MenuType.h"

namespace render {

  /// class MenuTileSet - 
  class MenuTileSet : public render::TileSet {
    // Associations
    // Attributes
  private:
    std::map<MenuType, Tile> menus;
    // Operations
  public:
    MenuTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (std::string menu) const;
    // Setters and Getters
  };

};

#endif
