// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace render {
  class TerrainLayer;
  class UnitLayer;
  class StateLayer;
  class DebugLayer;
  class MenuLayer;
};
namespace sf {
  class RenderWindow;
};
namespace state {
  class Terrain;
}

#include "TerrainLayer.h"
#include "UnitLayer.h"
#include "StateLayer.h"
#include "DebugLayer.h"
#include "MenuLayer.h"

namespace render {

  /// class Scene - 
  class Scene {
    // Associations
    // Attributes
  private:
    const state::State& state;
    TerrainLayer terrainLayer;
    UnitLayer unitLayer;
    StateLayer stateLayer;
    DebugLayer debugLayer;
    MenuLayer menuLayer;
  protected:
    bool menu     = false;
    int width     = 0;
    int heigh     = 0;
    int shiftWidth;
    int shiftHeight;
    // Operations
  public:
    Scene (const state::State& state);
    void stateChanged ();
    void draw (sf::RenderWindow& window);
    DebugLayer& getDebugLayer ();
    state::Terrain* getTerrainFromPositionOnWindow (int x, int y);
    // Setters and Getters
    bool getMenu() const;
    void setMenu(bool menu);
    int getWidth() const;
    void setWidth(int width);
    int getHeigh() const;
    void setHeigh(int heigh);
    int getShiftWidth() const;
    void setShiftWidth(int shiftWidth);
    int getShiftHeight() const;
    void setShiftHeight(int shiftHeight);
  };

};

#endif
