// Generated by dia2code
#ifndef RENDER__STATETILESET__H
#define RENDER__STATETILESET__H

#include <map>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "MenuTypeId.h"
#include "TileSet.h"

namespace render {

  /// class StateTileSet - 
  class StateTileSet : public render::TileSet {
    // Attributes
  private:
    std::map<MenuTypeId, Tile> menus;
    // Operations
  public:
    StateTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (MenuTypeId menu) const;
    // Setters and Getters
  };

};

#endif
