// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class Tile;
}

namespace render {

  /// class Surface - 
  class Surface {
    // Attributes
  public:
    sf::Texture texture;
    sf::VertexArray quads;
    // Operations
  public:
    void loadTexture (const std::string& image_file);
    void initQuads (int count);
    setSpriteLocation (int i, int x, int y);
    void setSpriteTexture (int i, const Tile& texture);
    /// 											
    /// @param target		(???) 
    /// @param states		(???) 
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    // Setters and Getters
  };

};

#endif
