// Generated by dia2code
#ifndef RENDER__TERRAINTILESIDE__H
#define RENDER__TERRAINTILESIDE__H

#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class TerrainTileSide - 
  class TerrainTileSide : public render::TileSet {
    // Operations
  public:
    /// 			
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (const state::Terrain& terrain) const;
    // Setters and Getters
  };

};

#endif
