// Generated by dia2code
#ifndef RENDER__TERRAINLAYER__H
#define RENDER__TERRAINLAYER__H


namespace state {
  class Board;
  class Terrain;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/Board.h"

namespace render {

  /// class TerrainLayer - 
  class TerrainLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::Board& board;
    // Operations
  public:
    TerrainLayer (const state::Board& board);
    void initSurface ();
    state::Terrain* getTerrainFromPositionOnWindow (int x, int y);
    // Setters and Getters
  };

};

#endif
