// Generated by dia2code
#ifndef RENDER__TERRAINTYPE__H
#define RENDER__TERRAINTYPE__H


namespace render {

  enum TerrainType {
    GRASS     = 1,
    FOREST     = 2,
    WATER     = 3,
    HOUSE     = 4,
    CASTLE     = 5,
    WALL_LEFT     = 6,
    WALL_TOP     = 7,
    WALL_RIGHT     = 8
  };

};

#endif
