// Generated by dia2code
#ifndef RENDER__TERRAINTYPE__H
#define RENDER__TERRAINTYPE__H


namespace render {

  enum TerrainType {
    GRASS     = 1,
    FOREST     = 2,
    WATER     = 3,
    HOUSE,
    CASTLE,
    WALL_LEFT,
    WALL_TOP,
    WALL_RIGHT
  };

};

#endif
