// Generated by dia2code
#ifndef RENDER__UNITTILESET__H
#define RENDER__UNITTILESET__H

#include <map>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Unit;
};
namespace render {
  class TileSet;
}

#include "TileSet.h"
#include "UnitType.h"

namespace render {

  /// class UnitTileSet - 
  class UnitTileSet : public render::TileSet {
    // Associations
    // Attributes
  private:
    std::map<UnitType,Tile> humans;
    std::map<UnitType,Tile> orcs;
    // Operations
  public:
    UnitTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    const std::string getImageFile () const;
    const Tile& getTile (const state::Unit& unit) const;
    // Setters and Getters
  };

};

#endif
