// Generated by dia2code
#ifndef RENDER__UNITTYPE__H
#define RENDER__UNITTYPE__H


namespace render {

  enum UnitType {
    HUMANLEADER     = 1,
    HUMANSWORDMAN     = 2,
    HUMANBOWMAN     = 3,
    ORCLEADER     = 4,
    ORCSWORDMAN     = 5,
    ORCBOWMAN     = 6
  };

};

#endif
