// Generated by dia2code
#ifndef RENDER__UNITLAYER__H
#define RENDER__UNITLAYER__H


namespace state {
  class Board;
};
namespace render {
  class Layer;
};
namespace state {
  class Observer;
}

#include "Layer.h"
#include "state/Observer.h"
#include "state/Board.h"

namespace render {

  /// class UnitLayer - 
  class UnitLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::Board& board;
    // Operations
  public:
    UnitLayer (const state::Board& board);
    void initSurface ();
    void stateChanged (const state::Event& event);
    void updateUnit (int i, int j);
    // Setters and Getters
  };

};

#endif
