// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace engine {
  class Command;
  class Engine;
};
namespace state {
  class State;
}

#include "state/TeamId.h"
#include "engine/Engine.h"
#include "engine/Command.h"
#include "state/State.h"

namespace ai {

  /// class AI - 
  class AI {
    // Operations
  public:
    virtual ~AI ();
    virtual engine::Command* run (engine::Engine& engine, state::TeamId player) = 0;
  protected:
    void listCommands (const state::State& state, std::vector<engine::Command*>& commands);
    void listCommandsMovement (const state::State& state, std::vector<engine::Command*>& commands);
    void listCommandsSpawn (const state::State& state, std::vector<engine::Command*>& commands);
    void listCommandsAttack (const state::State& state, std::vector<engine::Command*>& commands);
    // Setters and Getters
  };

};

#endif
