// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace ai {
  class PathMap;
};
namespace state {
  class Board;
};
namespace engine {
  class Command;
  class Engine;
};
namespace ai {
  class AI;
}

#include "PathMap.h"
#include "state/TeamId.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  protected:
    PathMap unitTeam1PathMap;
    PathMap unitTeam2PathMap;
    PathMap houseTeam1PathMap;
    PathMap houseTeam2PathMap;
    PathMap castlePathMap;
    // Operations
  public:
    HeuristicAI ();
    void initPathMaps (const state::Board& board);
    engine::Command* run (engine::Engine& engine, state::TeamId player);
    // Setters and Getters
    const PathMap& getUnitTeam1PathMap() const;
    void setUnitTeam1PathMap(const PathMap& unitTeam1PathMap);
    const PathMap& getUnitTeam2PathMap() const;
    void setUnitTeam2PathMap(const PathMap& unitTeam2PathMap);
    const PathMap& getHouseTeam1PathMap() const;
    void setHouseTeam1PathMap(const PathMap& houseTeam1PathMap);
    const PathMap& getHouseTeam2PathMap() const;
    void setHouseTeam2PathMap(const PathMap& houseTeam2PathMap);
    const PathMap& getCastlePathMap() const;
    void setCastlePathMap(const PathMap& castlePathMap);
  };

};

#endif
