// Generated by dia2code
#ifndef AI__PATHMAP__H
#define AI__PATHMAP__H

#include <vector>
#include <queue>

namespace ai {
  class Point;
};
namespace state {
  class Board;
};
namespace ai {
  class PointCompareWeight;
}

#include "Point.h"
#include "state/Board.h"
#include "PointCompareWeight.h"

namespace ai {

  /// class PathMap - 
  class PathMap {
    // Attributes
  private:
    int width     = 0;
    /// 				
    int height     = 0;
    std::vector<int> weights;
    std::priority_queue<Point, std::vector<Point>, PointCompareWeight> queue;
    // Operations
  public:
    int getWeight (const Point& p) const;
    /// 	
    /// @param p		(???) 
    void setWeight (const Point& p);
    std::vector<int> getWeights () const;
    void init (const state::Board& grid);
    void addSink (Point p);
    /// 			
    /// @param grid		(???) 
    void update (const state::Board& grid);
    // Setters and Getters
  };

};

#endif
