// Generated by dia2code
#ifndef AI__POINT__H
#define AI__POINT__H

#include <limits>

namespace ai {
  class Point;
}

#include "state/Direction.h"

namespace ai {

  /// class Point - 
  class Point {
    // Attributes
  protected:
    int x;
    int y;
    int weight;
    // Operations
  public:
    Point (int x, int y, int weight = std::numeric_limits<int>::max());
    Point transformToPoint (state::Direction d);
    state::Direction transformToDirection (Point p);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getWeight() const;
    void setWeight(int weight);
  };

};

#endif
