// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/WeaponTypeId.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    int idUnitAttacker;
    int idUnitDefender;
    state::WeaponTypeId weaponTypeId;
    // Operations
  public:
    AttackCommand (int idUnitAttacker, int idUnitDefender, state::WeaponTypeId weaponTypeId);
    /// 		
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
  private:
    void attackUnit (state::State& state, int idUnitAttacker, int idUnitDefender, state::WeaponTypeId weaponTypeId);
    /// 	
    /// @param state		(???) 
    /// @param idUnit		(???) 
    void killUnit (state::State& state, int idUnit);
    // Setters and Getters
  };

};

#endif
