// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <stack>
#include <memory>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "state/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getTypeId () const = 0;
    virtual void execute (state::State& state, std::stack<std::shared_ptr<Action>>& actions) = 0;
    virtual Command* clone () const = 0;
    virtual void serialize (Json::Value& out) const = 0;
    static Command* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
