// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 1,
    MOVE     = 2,
    ATTACK     = 3,
    SPAWN     = 4
  };

};

#endif
