// Generated by dia2code
#ifndef ENGINE__ENDTURNACTION__H
#define ENGINE__ENDTURNACTION__H

#include <map>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class EndTurnAction - 
  class EndTurnAction : public engine::Action {
    // Attributes
  protected:
    std::map<int, int> speeds;
    int gold;
    // Operations
  public:
    EndTurnAction ();
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
    const std::map<int, int>& getSpeeds() const;
    void setSpeeds(const std::map<int, int>& speeds);
    int getGold() const;
    void setGold(int gold);
  };

};

#endif
