// Generated by dia2code
#ifndef ENGINE__ENDTURNCOMMAND__H
#define ENGINE__ENDTURNCOMMAND__H

#include <stack>
#include <memory>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
  class EndTurnCommand;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class EndTurnCommand - 
  class EndTurnCommand : public engine::Command {
    // Operations
  public:
    EndTurnCommand ();
    CommandTypeId getTypeId () const;
    void execute (state::State& state, std::stack<std::shared_ptr<Action>>& actions);
    Command* clone () const;
    void serialize (Json::Value& out) const;
    static EndTurnCommand* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
