// Generated by dia2code
#ifndef ENGINE__HANDLEWINCOMMAND__H
#define ENGINE__HANDLEWINCOMMAND__H

#include <stack>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "Command.h"
#include "state/TeamId.h"

namespace engine {

  /// class HandleWinCommand - 
  class HandleWinCommand : public engine::Command {
    // Associations
    // Operations
  public:
    HandleWinCommand ();
    CommandTypeId getTypeId () const;
    void execute (state::State& state, std::stack<std::shared_ptr<Action>>& actions);
    // Setters and Getters
  };

};

#endif
