// Generated by dia2code
#ifndef ENGINE__HANDLEWINCOMMAND__H
#define ENGINE__HANDLEWINCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "state/TeamId.h"
#include "state/UnitTypeId.h"

namespace engine {

  /// class HandleWinCommand - 
  class HandleWinCommand : public engine::Command {
    // Associations
    // Operations
  public:
    HandleWinCommand ();
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
