// Generated by dia2code
#ifndef ENGINE__HANDLESPAWNCOMMAND__H
#define ENGINE__HANDLESPAWNCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class HandleSpawnCommand - 
  class HandleSpawnCommand : public engine::Command {
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
  private:
    void spawnUnit (state::UnitTypeId unitTypeId);
    // Setters and Getters
  };

};

#endif
