// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H

#include <string>
#include <stack>
#include <memory>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class Command;
  class LoadCommand;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  protected:
    std::string fileName;
    // Operations
  public:
    LoadCommand (const std::string fileName);
    CommandTypeId getTypeId () const;
    void execute (state::State& state, std::stack<std::shared_ptr<Action>>& actions);
    Command* clone () const;
    void serialize (Json::Value& out) const;
    static LoadCommand* deserialize (const Json::Value& in);
    // Setters and Getters
    const std::string& getFileName() const;
    void setFileName(const std::string& fileName);
  };

};

#endif
