// Generated by dia2code
#ifndef ENGINE__MOVEACTION__H
#define ENGINE__MOVEACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "state/Direction.h"
#include "Action.h"

namespace engine {

  /// class MoveAction - 
  class MoveAction : public engine::Action {
    // Attributes
  protected:
    int idUnit;
    int x;
    int y;
    state::Direction direction;
    // Operations
  public:
    MoveAction (int idUnit, state::Direction direction);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
    int getIdUnit() const;
    void setIdUnit(int idUnit);
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    state::Direction getDirection() const;
    void setDirection(state::Direction direction);
  };

};

#endif
