// Generated by dia2code
#ifndef ENGINE__WINNERACTION__H
#define ENGINE__WINNERACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "state/TeamId.h"
#include "Action.h"

namespace engine {

  /// class WinnerAction - 
  class WinnerAction : public engine::Action {
    // Attributes
  protected:
    state::TeamId teamId;
    // Operations
  public:
    WinnerAction (state::TeamId teamId);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
    state::TeamId getTeamId() const;
    void setTeamId(state::TeamId teamId);
  };

};

#endif
