// Generated by dia2code
#ifndef SERVER__COMMANDSERVICE__H
#define SERVER__COMMANDSERVICE__H

#include <json/json.h>

namespace engine {
  class Engine;
};
namespace server {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "engine/Engine.h"

namespace server {

  /// class CommandService - 
  class CommandService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    /// 				
    engine::Engine& engine;
    // Operations
  public:
    CommandService (engine::Engine& engine);
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus post (Json::Value& out, const Json::Value& in);
    // Setters and Getters
  };

};

#endif
