// Generated by dia2code
#ifndef SERVER__GAME__H
#define SERVER__GAME__H

#include <map>

namespace server {
  class Player;
}

#include "Player.h"

namespace server {

  /// class Game - 
  class Game {
    // Associations
    // Attributes
  private:
    std::map<int, Player> players;
    // Operations
  public:
    Game ();
    Player& getPlayer (int id);
    // Setters and Getters
  };

};

#endif
