// Generated by dia2code
#ifndef SERVER__HTTPSTATUS__H
#define SERVER__HTTPSTATUS__H


namespace server {

  enum HttpStatus {
    OK,
    CREATED,
    NO_CONTENT,
    BAD_REQUEST,
    NOT_FOUND,
    SERVER_ERROR,
    NOT_IMPLEMENTED
  };

};

#endif
