// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H

#include <string>

#include "state/TeamId.h"

namespace server {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  public:
    /// 				
    std::string name;
    state::TeamId teamId;
    bool free     = true;
    // Operations
  public:
    Player (std::string name, bool free);
    // Setters and Getters
  };

};

#endif
