// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Action.h"
#include "engine/Command.h"
#include "engine/Observer.h"
#include "engine/Observable.h"
#include "engine/Engine.h"
#include "engine/MoveCommand.h"
#include "engine/LoadCommand.h"
#include "engine/AttackCommand.h"
#include "engine/SpawnCommand.h"
#include "engine/EndTurnCommand.h"
#include "engine/HandleWinCommand.h"
#include "engine/MoveAction.h"
#include "engine/AttackAction.h"
#include "engine/SpawnAction.h"
#include "engine/EndTurnAction.h"
#include "engine/WinnerAction.h"
#endif
