// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <SFML/Graphics.hpp>

namespace engine {
  class Engine;
};
namespace render {
  class Scene;
};
namespace engine {
  class Command;
}

#include "render/Scene.h"
#include "state/TeamId.h"
#include "engine/Command.h"
#include "engine/Engine.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  public:
    state::UnitTypeId unitSpawnTypeId     = state::UnitTypeId::INVALID_UNIT;
  private:
    /// 			
    const int windowWidth     = 1188;
    const int windowHeight     = 576;
    engine::Engine& engine;
    render::Scene scene;
    sf::Vector2i startMousePos;
    sf::RenderWindow window;
    int mode     = 0;
    state::TeamId teamId;
    state::Terrain* startingTerrain     = nullptr;
    state::Terrain* targetTerrain     = nullptr;
    // Operations
  public:
    Client (engine::Engine& engine, state::TeamId teamId);
    engine::Command* generateCommand ();
    void displayMenu ();
    void displayBoard ();
    void displaySpawn ();
    void run ();
    // Setters and Getters
  };

};

#endif
