// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace engine {
  class Engine;
  class Command;
}

#include "state/TeamId.h"
#include "engine/Command.h"
#include "engine/Engine.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  private:
    state::TeamId teamId;
    engine::Engine& engine;
    int selectedUnitId;
    // Operations
  public:
    Client (engine::Engine& engine, state::TeamId teamId);
    engine::Command* generateCommand (int x, int y);
    void run ();
    // Setters and Getters
  };

};

#endif
