// Generated by dia2code
#ifndef CLIENT__NETWORKCLIENT__H
#define CLIENT__NETWORKCLIENT__H

#include <string>
#include <memory>
#include <json/json.h>

namespace ai {
  class AI;
};
namespace engine {
  class Engine;
  class Command;
};
namespace render {
  class Scene;
}

#include "ai/AI.h"
#include "state/TeamId.h"
#include "engine/Engine.h"
#include "render/Scene.h"

namespace client {

  /// class NetworkClient - 
  class NetworkClient {
    // Associations
    // Attributes
  private:
    std::string url;
    int port;
    std::string player;
    std::unique_ptr<ai::AI> player_ai;
    state::TeamId teamId;
    engine::Engine engine;
    int idPlayer;
    // Operations
  public:
    NetworkClient (const std::string& url, int port, std::string player);
    std::string getGameStatus ();
    bool getServerCommands (Json::Value& out, int epoch);
    void putServerCommand (engine::Command* command);
    void endConnection ();
    void run ();
    // Setters and Getters
  };

};

#endif
